export const ways = [
    {
        name: "Personal",
        name_bottom: "Special first packet for all",
        price: "$8",
        price_right: "/Month",
        text1: "Up to 5 page each group",
        text2: "Up to 10 group page",
        text3: "5 Days group page saved",
    },
    {
        name: "Regular",
        name_bottom: "Recommended for personal pro",
        price: "$20",
        price_right: "/Month",
        text1: "Up to 15 page each group",
        text2: "Download page up to 20 page",
        text3: "Up to 10 group page",
        text4: "15 Days group page saved",
    },
    {
        name: "Premium",
        name_bottom: "Packet for Startup & Company",
        price: "$48",
        price_right: "/Month",
        text1: "Unlimited group pages",
        text2: "Unlimited download page",
        text3: "Unlimited page each group",
        text4: "Customize sorting group pages",
        text5: "Customize group page name",
        text6: "30 Days group page saved",
    },
]